/* tslint:disable */
/* eslint-disable */
/**
 * DuckDuckFit Exercise Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@duckduckfit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ExerciseOntoMovementPatternsInnerInner } from './ExerciseOntoMovementPatternsInnerInner';
import {
    ExerciseOntoMovementPatternsInnerInnerFromJSON,
    ExerciseOntoMovementPatternsInnerInnerFromJSONTyped,
    ExerciseOntoMovementPatternsInnerInnerToJSON,
    ExerciseOntoMovementPatternsInnerInnerToJSONTyped,
} from './ExerciseOntoMovementPatternsInnerInner';

/**
 * 
 * @export
 * @interface ExerciseOnto
 */
export interface ExerciseOnto {
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseOnto
     */
    targetMuscles: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseOnto
     */
    synergistMuscles: Array<string>;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExerciseOnto
     */
    equipment: Array<string>;
    /**
     * 
     * @type {Array<Array<ExerciseOntoMovementPatternsInnerInner>>}
     * @memberof ExerciseOnto
     */
    movementPatterns: Array<Array<ExerciseOntoMovementPatternsInnerInner>>;
}

/**
 * Check if a given object implements the ExerciseOnto interface.
 */
export function instanceOfExerciseOnto(value: object): value is ExerciseOnto {
    if (!('targetMuscles' in value) || value['targetMuscles'] === undefined) return false;
    if (!('synergistMuscles' in value) || value['synergistMuscles'] === undefined) return false;
    if (!('equipment' in value) || value['equipment'] === undefined) return false;
    if (!('movementPatterns' in value) || value['movementPatterns'] === undefined) return false;
    return true;
}

export function ExerciseOntoFromJSON(json: any): ExerciseOnto {
    return ExerciseOntoFromJSONTyped(json, false);
}

export function ExerciseOntoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseOnto {
    if (json == null) {
        return json;
    }
    return {
        
        'targetMuscles': json['target_muscles'],
        'synergistMuscles': json['synergist_muscles'],
        'equipment': json['equipment'],
        'movementPatterns': json['movement_patterns'],
    };
}

export function ExerciseOntoToJSON(json: any): ExerciseOnto {
    return ExerciseOntoToJSONTyped(json, false);
}

export function ExerciseOntoToJSONTyped(value?: ExerciseOnto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'target_muscles': value['targetMuscles'],
        'synergist_muscles': value['synergistMuscles'],
        'equipment': value['equipment'],
        'movement_patterns': value['movementPatterns'],
    };
}

