/* tslint:disable */
/* eslint-disable */
/**
 * DuckDuckFit Exercise Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@duckduckfit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ExerciseOntoMovementPatternsInnerInner
 * 
 * @export
 */
export type ExerciseOntoMovementPatternsInnerInner = string;

export function ExerciseOntoMovementPatternsInnerInnerFromJSON(json: any): ExerciseOntoMovementPatternsInnerInner {
    return ExerciseOntoMovementPatternsInnerInnerFromJSONTyped(json, false);
}

export function ExerciseOntoMovementPatternsInnerInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExerciseOntoMovementPatternsInnerInner {
    if (json == null) {
        return json;
    }
    if (instanceOfstring(json)) {
        return stringFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ExerciseOntoMovementPatternsInnerInnerToJSON(json: any): any {
    return ExerciseOntoMovementPatternsInnerInnerToJSONTyped(json, false);
}

export function ExerciseOntoMovementPatternsInnerInnerToJSONTyped(value?: ExerciseOntoMovementPatternsInnerInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

