/* tslint:disable */
/* eslint-disable */
/**
 * DuckDuckFit Exercise Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@duckduckfit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Article } from './Article';
import {
    ArticleFromJSON,
    ArticleFromJSONTyped,
    ArticleToJSON,
    ArticleToJSONTyped,
} from './Article';

/**
 * 
 * @export
 * @interface GetArticles200Response
 */
export interface GetArticles200Response {
    /**
     * 
     * @type {Array<Article>}
     * @memberof GetArticles200Response
     */
    items?: Array<Article>;
    /**
     * Maximal number of items to send.
     * @type {number}
     * @memberof GetArticles200Response
     */
    limit?: number;
    /**
     * Offset from the beginning of the query.
     * @type {number}
     * @memberof GetArticles200Response
     */
    offset?: number;
    /**
     * Total number of items.
     * @type {number}
     * @memberof GetArticles200Response
     */
    total?: number;
}

/**
 * Check if a given object implements the GetArticles200Response interface.
 */
export function instanceOfGetArticles200Response(value: object): value is GetArticles200Response {
    return true;
}

export function GetArticles200ResponseFromJSON(json: any): GetArticles200Response {
    return GetArticles200ResponseFromJSONTyped(json, false);
}

export function GetArticles200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetArticles200Response {
    if (json == null) {
        return json;
    }
    return {

        'items': json['items'] == null ? null : ((json['items'] as Array<any>).map(ArticleFromJSON)),
        'limit': json['limit'] == null ? null : json['limit'],
        'offset': json['offset'] == null ? null : json['offset'],
        'total': json['total'] == null ? null : json['total'],
    };
}

export function GetArticles200ResponseToJSON(json: any): GetArticles200Response {
    return GetArticles200ResponseToJSONTyped(json, false);
}

export function GetArticles200ResponseToJSONTyped(value?: GetArticles200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': value['items'] == null ? null : ((value['items'] as Array<any>).map(ArticleToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

