/* tslint:disable */
/* eslint-disable */
/**
 * DuckDuckFit Exercise Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@duckduckfit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';

/**
 * Validation Exception
 * @export
 * @interface GetExerciseById400Response
 */
export interface GetExerciseById400Response {
    /**
     * 
     * @type {number}
     * @memberof GetExerciseById400Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof GetExerciseById400Response
     */
    detail: string;
    /**
     * 
     * @type {{ [key: string]: any | undefined; }}
     * @memberof GetExerciseById400Response
     */
    extra?: { [key: string]: any | undefined; };
}

/**
 * Check if a given object implements the GetExerciseById400Response interface.
 */
export function instanceOfGetExerciseById400Response(value: object): value is GetExerciseById400Response {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function GetExerciseById400ResponseFromJSON(json: any): GetExerciseById400Response {
    return GetExerciseById400ResponseFromJSONTyped(json, false);
}

export function GetExerciseById400ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExerciseById400Response {
    if (json == null) {
        return json;
    }
    return {

        'statusCode': json['status_code'],
        'detail': json['detail'],
        'extra': json['extra'] == null ? null : json['extra'],
    };
}

export function GetExerciseById400ResponseToJSON(json: any): GetExerciseById400Response {
    return GetExerciseById400ResponseToJSONTyped(json, false);
}

export function GetExerciseById400ResponseToJSONTyped(value?: GetExerciseById400Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'status_code': value['statusCode'],
        'detail': value['detail'],
        'extra': value['extra'],
    };
}

