/* tslint:disable */
/* eslint-disable */
/**
 * DuckDuckFit Exercise Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@duckduckfit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Exercise } from './Exercise';
import {
    ExerciseFromJSON,
    ExerciseFromJSONTyped,
    ExerciseToJSON,
    ExerciseToJSONTyped,
} from './Exercise';

/**
 * 
 * @export
 * @interface GetExercises200Response
 */
export interface GetExercises200Response {
    /**
     * 
     * @type {Array<Exercise>}
     * @memberof GetExercises200Response
     */
    items?: Array<Exercise>;
    /**
     * Maximal number of items to send.
     * @type {number}
     * @memberof GetExercises200Response
     */
    limit?: number;
    /**
     * Offset from the beginning of the query.
     * @type {number}
     * @memberof GetExercises200Response
     */
    offset?: number;
    /**
     * Total number of items.
     * @type {number}
     * @memberof GetExercises200Response
     */
    total?: number;
}

/**
 * Check if a given object implements the GetExercises200Response interface.
 */
export function instanceOfGetExercises200Response(value: object): value is GetExercises200Response {
    return true;
}

export function GetExercises200ResponseFromJSON(json: any): GetExercises200Response {
    return GetExercises200ResponseFromJSONTyped(json, false);
}

export function GetExercises200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExercises200Response {
    if (json == null) {
        return json;
    }
    return {

        'items': json['items'] == null ? null : ((json['items'] as Array<any>).map(ExerciseFromJSON)),
        'limit': json['limit'] == null ? null : json['limit'],
        'offset': json['offset'] == null ? null : json['offset'],
        'total': json['total'] == null ? null : json['total'],
    };
}

export function GetExercises200ResponseToJSON(json: any): GetExercises200Response {
    return GetExercises200ResponseToJSONTyped(json, false);
}

export function GetExercises200ResponseToJSONTyped(value?: GetExercises200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'items': value['items'] == null ? null : ((value['items'] as Array<any>).map(ExerciseToJSON)),
        'limit': value['limit'],
        'offset': value['offset'],
        'total': value['total'],
    };
}

