/* tslint:disable */
/* eslint-disable */
/**
 * DuckDuckFit Exercise Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@duckduckfit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Not Found Exception
 * @export
 * @interface GetExerciseById404Response
 */
export interface GetExerciseById404Response {
    /**
     * 
     * @type {number}
     * @memberof GetExerciseById404Response
     */
    statusCode: number;
    /**
     * 
     * @type {string}
     * @memberof GetExerciseById404Response
     */
    detail: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof GetExerciseById404Response
     */
    extra?: { [key: string]: any; };
}

/**
 * Check if a given object implements the GetExerciseById404Response interface.
 */
export function instanceOfGetExerciseById404Response(value: object): value is GetExerciseById404Response {
    if (!('statusCode' in value) || value['statusCode'] === undefined) return false;
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function GetExerciseById404ResponseFromJSON(json: any): GetExerciseById404Response {
    return GetExerciseById404ResponseFromJSONTyped(json, false);
}

export function GetExerciseById404ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GetExerciseById404Response {
    if (json == null) {
        return json;
    }
    return {

        'statusCode': json['status_code'],
        'detail': json['detail'],
        'extra': json['extra'] == null ? undefined : json['extra'],
    };
}

export function GetExerciseById404ResponseToJSON(json: any): GetExerciseById404Response {
    return GetExerciseById404ResponseToJSONTyped(json, false);
}

export function GetExerciseById404ResponseToJSONTyped(value?: GetExerciseById404Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {

        'status_code': value['statusCode'],
        'detail': value['detail'],
        'extra': value['extra'],
    };
}

