/* tslint:disable */
/* eslint-disable */
/**
 * DuckDuckFit Exercise Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@duckduckfit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthCheck
 */
export interface HealthCheck {
    /**
     * 
     * @type {string}
     * @memberof HealthCheck
     */
    dbStatus: HealthCheckDbStatusEnum;
    /**
     * 
     * @type {Date}
     * @memberof HealthCheck
     */
    timestamp: Date;
}


/**
 * @export
 */
export const HealthCheckDbStatusEnum = {
    Online: 'online',
    Offline: 'offline'
} as const;
export type HealthCheckDbStatusEnum = typeof HealthCheckDbStatusEnum[keyof typeof HealthCheckDbStatusEnum];


/**
 * Check if a given object implements the HealthCheck interface.
 */
export function instanceOfHealthCheck(value: object): value is HealthCheck {
    if (!('dbStatus' in value) || value['dbStatus'] === undefined) return false;
    if (!('timestamp' in value) || value['timestamp'] === undefined) return false;
    return true;
}

export function HealthCheckFromJSON(json: any): HealthCheck {
    return HealthCheckFromJSONTyped(json, false);
}

export function HealthCheckFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthCheck {
    if (json == null) {
        return json;
    }
    return {
        
        'dbStatus': json['db_status'],
        'timestamp': (new Date(json['timestamp'])),
    };
}

export function HealthCheckToJSON(json: any): HealthCheck {
    return HealthCheckToJSONTyped(json, false);
}

export function HealthCheckToJSONTyped(value?: HealthCheck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'db_status': value['dbStatus'],
        'timestamp': ((value['timestamp']).toISOString()),
    };
}

