/* tslint:disable */
/* eslint-disable */
/**
 * DuckDuckFit Exercise Database API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: contact@duckduckfit.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Locale
 */
export interface Locale {
    /**
     * The ISO 639-1 language code
     * @type {string}
     * @memberof Locale
     */
    iso6391: string;
    /**
     * The name of the language in English.
     * @type {string}
     * @memberof Locale
     */
    isoLabel: string;
    /**
     * The name of the language in its native orthography.
     * @type {string}
     * @memberof Locale
     */
    endonym: string;
}

/**
 * Check if a given object implements the Locale interface.
 */
export function instanceOfLocale(value: object): value is Locale {
    if (!('iso6391' in value) || value['iso6391'] === undefined) return false;
    if (!('isoLabel' in value) || value['isoLabel'] === undefined) return false;
    if (!('endonym' in value) || value['endonym'] === undefined) return false;
    return true;
}

export function LocaleFromJSON(json: any): Locale {
    return LocaleFromJSONTyped(json, false);
}

export function LocaleFromJSONTyped(json: any, ignoreDiscriminator: boolean): Locale {
    if (json == null) {
        return json;
    }
    return {
        
        'iso6391': json['iso_6391'],
        'isoLabel': json['iso_label'],
        'endonym': json['endonym'],
    };
}

export function LocaleToJSON(json: any): Locale {
    return LocaleToJSONTyped(json, false);
}

export function LocaleToJSONTyped(value?: Locale | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'iso_6391': value['iso6391'],
        'iso_label': value['isoLabel'],
        'endonym': value['endonym'],
    };
}

