apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duckduckfit.fullname" . }}-environment
  labels:
    {{- include "duckduckfit.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}
