apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "duckduckfit_ui.fullname" . }}-environment
  labels:
    {{- include "duckduckfit_ui.labels" . | nindent 4 }}
data:
{{ toYaml .Values.env | indent 2 }}
