apiVersion: v1
kind: Service
metadata:
  name: { { include "duckduckfit.fullname" . } }
  labels: { { - include "duckduckfit.labels" . | nindent 4 } }
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector: { { - include "duckduckfit.selectorLabels" . | nindent 4 } }
