name: Web

on:
  push:
    branches: [main]

jobs:
  pages:
    runs-on: ubuntu-latest
    env:
      PUBLIC_URL: https://faucett-gmbh.github.io/ts-duckduckfit
      PUBLIC_EXDB_URL: https://exdb.faucett-gmbh.com
      PUBLIC_P2P_API_URL: https://p2p.aicacia.com
      PUBLIC_P2P_WS_URL: wss://p2p.aicacia.com
      USE_BASE_PATH: true
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: npm install -g pnpm@10
      - run: pnpm install --no-frozen-lockfile
      - run: NODE_ENV=production pnpm build

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
